package ca.braelor.l1ghtsword.assignment.model.enums;

//Enum for skill titles, constants that will not change used to associate any skill check with an item on the list
public enum ItemSlot {
    SLOT_1,
    SLOT_2,
    SLOT_3,
    SLOT_4,
    SLOT_5,
    SLOT_6,
    SLOT_7,
    SLOT_8,
    SLOT_9,
    SLOT_10,
    SLOT_11,
    SLOT_12,
    SLOT_13,
    SLOT_14,
    SLOT_15,
    SLOT_16,
    SLOT_17,
    SLOT_18,
    SLOT_19,
    SLOT_20,
    SLOT_21,
    SLOT_22,
    SLOT_23,
    SLOT_24,
    SLOT_25,
    SLOT_26,
    SLOT_27,
    SLOT_28,
    SLOT_29,
    SLOT_30,
    SLOT_31,
    SLOT_32,
    SLOT_33,
    SLOT_34,
    SLOT_35,
    SLOT_36,
}
